# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AppImage Crafters
email: contact@azubieta.net
description: > # this means to ignore newlines until "baseurl:"
  AppImage creation an usage.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://appimagecrafters.github.io/" # the base hostname & protocol for your site
github_username:  appimagecrafters

# Build settings
markdown: kramdown
